// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CardValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("card")]
        public Card Card { get; set; }

        [JsonProperty("cardNumber")]
        public string CardNumber { get; set; }

        [JsonProperty("isValid")]
        public bool IsValid { get; set; }
    }

    public partial class Card
    {
        [JsonProperty("niceType")]
        public string NiceType { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("patterns")]
        public long[] Patterns { get; set; }

        [JsonProperty("gaps")]
        public long[] Gaps { get; set; }

        [JsonProperty("lengths")]
        public long[] Lengths { get; set; }

        [JsonProperty("code")]
        public Code Code { get; set; }

        [JsonProperty("matchStrength")]
        public long MatchStrength { get; set; }
    }

    public partial class Code
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("size")]
        public long Size { get; set; }
    }
}
